package com.industria.coordinacion.ui

import androidx.compose.foundation.*
import kotlinx.coroutines.withTimeout
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.sistema.distribuido.network.IndustrialVisionAnalyzer
import com.sistema.distribuido.network.prefecto.IndustrialTheme
import com.sistema.distribuido.network.prefecto.IndustrialCard
import com.sistema.distribuido.network.prefecto.IndustrialActionButton
import com.sistema.distribuido.network.prefecto.IndustrialTextField
import kotlinx.coroutines.launch

@Composable
fun ArucoGeneratorTab(
    onGenerateAruco: (String) -> Unit,
    onUseWithLaser: (String) -> Unit = {},
    enabled: Boolean = true,
    modifier: Modifier = Modifier
) {
    var arucoId by remember { mutableStateOf("1") }
    var sizePx by remember { mutableStateOf("250") }
    var isGenerated by remember { mutableStateOf(false) }
    var generatedBitmap by remember { mutableStateOf<android.graphics.Bitmap?>(null) }
    var isGenerating by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()

    LazyColumn(
        modifier = modifier.fillMaxSize().padding(horizontal = 16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        item {
            IndustrialCard("Generador de Marcadores", Icons.Default.QrCode) {
                IndustrialTextField(
                    valor = arucoId, 
                    onValueChange = { arucoId = it.take(2) }, 
                    label = "ID del Marcador (0-49)"
                )
                Spacer(Modifier.height(8.dp))
                IndustrialTextField(
                    valor = sizePx, 
                    onValueChange = { sizePx = it.take(4) }, 
                    label = "Tamaño de Impresión (PX, recomendado 250-500)"
                )
                Spacer(Modifier.height(16.dp))
                IndustrialActionButton(
                    texto = if (isGenerating) "Generando..." else "Generar Pattern", 
                    icono = Icons.Default.Autorenew, 
                    loading = isGenerating,
                    enabled = enabled,
                    onClick = { 
                        scope.launch {
                            isGenerating = true
                            try {
                                val id = arucoId.toIntOrNull() ?: 1
                                val size = sizePx.toIntOrNull() ?: 250
                                generatedBitmap = IndustrialVisionAnalyzer.generateArucoMarker(id, size)
                                if (generatedBitmap != null) {
                                    isGenerated = true
                                    onGenerateAruco("ID:$id|SIZE:$size")
                                }
                            } catch (e: Exception) {
                                android.util.Log.e("ArucoGen", "Error: ${e.message}")
                            } finally {
                                isGenerating = false
                            }
                        }
                    }
                )
            }
        }

        if (isGenerated && generatedBitmap != null) {
            item {
                IndustrialCard("Vista Previa del Marcador", Icons.Default.Visibility) {
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(280.dp)
                            .background(Color.White, androidx.compose.foundation.shape.RoundedCornerShape(4.dp))
                            .padding(16.dp),
                        contentAlignment = Alignment.Center
                    ) {
                        // Mostrar imagen real del ArUco generado
                        Image(
                            bitmap = generatedBitmap!!.asImageBitmap(),
                            contentDescription = "ArUco Marcador ${arucoId}",
                            modifier = Modifier.fillMaxSize(),
                            contentScale = ContentScale.Fit
                        )
                    }
                    Spacer(Modifier.height(12.dp))
                    Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        IndustrialActionButton(
                            texto = "Enviar a Láser", 
                            icono = Icons.Default.FlashOn, 
                            modifier = Modifier.weight(1f),
                            colorFondo = IndustrialTheme.Advertencia,
                            enabled = enabled,
                            onClick = { onUseWithLaser("ARUCO_${arucoId}") }
                        )
                        IndustrialActionButton(
                            texto = "Guardar", 
                            icono = Icons.Default.Save, 
                            modifier = Modifier.weight(1f),
                            colorFondo = IndustrialTheme.Exito,
                            enabled = enabled,
                            onClick = { isGenerated = false; generatedBitmap = null }
                        )
                    }
                }
            }
        }

        item {
            IndustrialCard("Diccionarios Disponibles", Icons.Default.List) {
                Text("• DICT_4X4_50 (IDs 0-49, Optimizado)", color = IndustrialTheme.TextoPrincipal, fontSize = 12.sp, fontWeight = FontWeight.Bold)
                Text("• DICT_5X5_100 (IDs 0-99, Alta Precisión)", color = IndustrialTheme.TextoSecundario, fontSize = 12.sp)
                Text("• DICT_6X6_250 (IDs 0-249, Máximo Rango)", color = IndustrialTheme.TextoSecundario, fontSize = 12.sp)
                Spacer(Modifier.height(8.dp))
                Text("Usando actualmente: DICT_4X4_50", color = IndustrialTheme.Exito, fontSize = 11.sp, fontWeight = FontWeight.Bold)
            }
        }
    }
}
